<!DOCTYPE html>
<html lang="ru">
<head>
<meta charset="utf-8">
<title>Реставрация ванн в Гродно и в области: Без запаха и пыли! 100% Гарантия качества!</title>
<meta name="description" content="Эмалировка ванн, наливная ванна, акриловый вкладыш. Профессиональная реставрация ванн в Гродно, Щучине, Скиделе, Лиде, Волковыске, Слониме, Вороново, Берестовице и по всей Гродненской области." />
<meta name="keywords" content="" />
<meta name="Robots" content="index,follow" />
<link href="favicon.ico" rel="shortcut icon" type="image/x-icon" />
<meta name="viewport" content="width=device-width, initial-scale=1">
<link href="main.css" type="text/css" rel="stylesheet" />
<script type="text/javascript" src="dynamicsjs.js"></script>
<!-- Google Tag Manager -->
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-WWV5NHP');</script>
<!-- End Google Tag Manager -->
<script type="text/javascript" > (function(m,e,t,r,i,k,a){m[i]=m[i]||function(){(m[i].a=m[i].a||[]).push(arguments)}; m[i].l=1*new Date();k=e.createElement(t),a=e.getElementsByTagName(t)[0],k.async=1,k.src=r,a.parentNode.insertBefore(k,a)}) (window, document, "script", "https://mc.yandex.ru/metrika/tag.js", "ym"); ym(51498074, "init", { id:51498074, clickmap:true, trackLinks:true, accurateTrackBounce:true, webvisor:true }); </script> <noscript><div><img src="https://mc.yandex.ru/watch/51498074" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
</head>
<body><!-- Google Tag Manager (noscript) -->
<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-WWV5NHP"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<!-- End Google Tag Manager (noscript) -->
<header>
<div id="HamburgerMenu"><input id="toggle" type="checkbox"><label class="toggle-container" for="toggle"><span class="button button-toggle"></span></label><nav class="nav"><a class="nav-item" href="#mainpage">Главная</a><a class="nav-item" href="#Land1">Что лучше?</a><a class="nav-item" href="#uslugi">Способы реставрации</a><a class="nav-item" href="#process_restavracii">Процесс реставрации</a><a class="nav-item" href="#naschi_raboti">Наши работы</a><a class="nav-item" href="#otzivi">Отзывы</a><a class="nav-item" href="#sertificats">Сертификаты</a><a class="nav-item" href="#cena">Наши цены</a></nav></div>
<div id="wrappMenu"><div id="menu"><ul><li><a href="#mainpage">Главная</a></li><li><a href="#uslugi">Услуги</a></li><li><a href="#process_restavracii">Процесс</a></li><li><a href="#naschi_raboti">Наши работы</a></li><li><a href="#otzivi">Отзывы</a></li><li><a href="#sertificats">Сертификаты</a></li><li class="lastLi"><a href="#cena">Стоимость</a></li></ul></div></div>
<div id="mainpage" class="wrappHeader">
<div class="headerOtstup"></div>
<div id="header" class="cBlock">
<div id="logo"><a href="/grodno/" title="vanna-lux.by: Реставрация ванн в Гродно, Щучине, Волковыске, Слониме, Новогрудке, Мостах, Лиде, Скиделе: эмалировка ванн, наливная ванна, акриловый вкладыш.">
<div class="logostroka"><img id="logoimg" src="../images/logo.svg" alt="Покрытие ванн жидким акрилом, эмалировка ванн и акриловый вкладыш в Гродно и по всей Гродненской области."><h2 class="logoSiteH2">Vanna-lux.by</h2></div><p>Профессиональная реставрация ванн</p></a>
</div>
<div id="phones"><div class="phoneImg"><img src="images/a1_logo.png" alt="Заказать реставрацию ванны в Гродно и в Гродненской области."><div class="numberphone"><a class="header_phone" href="tel:+375296954525">+375(29) 695-45-25</a></div></div><div class="phoneImg mtsPhone"><img class="mtslogo" src="images/mtc.png" alt="Заказать восстановление ванны в Гродно и в Гродненской области."><div class="numberphone"><a class="header_phone" href="tel:+375292504525">+375(29) 250-45-25</a></div></div><div class="timework">ежедневно с 8.00 до 22.00</div>
<div class="consult_Div"><span class="consult" onclick="openModalBoxOrder('получить консультацию телефоны в шапке, ванна люкс Гродно')">Консультация у мастера</span></div>
</div>
<div class="wrapTtlHeader"><div id="titleHeader"><h2>Реставрация ванн, раковин и душевых поддонов в Гродно и по всей Гродненской области.</h2></div></div>
</div></div><div class="clear"></div>
</header>
<div class="main_img"><div class="cBlock"><h1 class="res_1">Полное восстановление вашей ванны!</h1><h2 class="res_2">Ваша ванна станет как новая!</h2>
<div class="mainTriggers"><div><div class="check"></div><h3>Без запаха, пыли и грязи!</h3></div><div><div class="check"></div><h3>Безопасно для здоровья!</h3></div><div><div class="check"></div><h3>Не желтеет и не темнеет!</h3></div><div><div class="check"></div><h3>Cертифицирован в Беларуси!</h3></div><div><div class="check"></div><h3>Используется в Европе и США!</h3></div><div><div class="check"></div><h3>Срок службы до 20 лет!</h3></div></div></div></div><div class="clear"></div>
<div id="Land1"><div class="cBlock"><h1 class="chto_luchsche">Что лучше?</h1><h2 class="mainzaglavie2">Покупка новой или реставрация старой ванны?</h2>
<div class="srvnRestor"><h2 class="srvnZagl">Реставрация старой ванны:</h2><h3>- Демонтаж ванны</h3><p>Не требуется. Нет пыли и грязи!</p><h3>- Время работы</h3><p>2 - 3 часа работы!</p><h3>- Срок службы</h3><p>Покрытие из хорошего наливного акрила прослужит до 20 лет!</p><h3>- Цена</h3><p>Дешевле чем покупка новой ванны в несколько раз!</p><h3>- Нестандартные размеры ванн</h3><p>Можно реставрировать ванны любых размеров!</p></div>
<div class="sravnNewVanna"><h2 class="srvnZagl">Покупка новой ванны:</h2><h3>- Демонтаж ванны</h3><p>Требуется. Много пыли и грязи. Неизбежна порча плитки.</p><h3>- Время работы</h3><p>от 2-ух до 5-ти дней.</p><h3>- Срок службы</h3><p>Зависит от качества новой ванны.</p><h3>- Цена</h3><p>Новая ванна от 200 руб. + сопутствующие расходы от 300 руб.</p><h3>- Нестандартные размеры ванн</h3><p>Если планируете нестандартную ванну, то неизбежен капитальный ремонт.</p></div>
<div class="clear"></div><div class="land1_readmore" onclick="openModalBoxPodrobno_Block_land_1()"><span>Подробнее</span></div></div>
<div id="Wrap_Podrobno_Block_land_1"><div id="Podrobno_Block_land_1_Schadow" class="shadow"></div>
<div class="relatives_for_close">
<div id="Block_land_1_Close" class="close"><img src="images/Bg/close.png" alt="Покрытие ванн жидким акрилом и эмалями в Гродно"></div>
<div id="Podrobno_Block_land_1"><h2 class="_H1">Реставрация ванн, что это?</h2>
<img src="images/land1.jpg" class="borderBlocks" alt="реставрация ванн в Гродно, наливная ванна в Гродно, акриловый вкладыш.">
<p><strong>Реставрация ванн</strong> - общее название услуг по восстановлению эмалевого покрытия ванны, направленных на продление срока ее эксплуатации.</p>
<p>Мы оказываем полный комплекс услуг в сфере <strong>реставрации чугунных, стальных и акриловых ванн в Гродно и по всем городам Гродненской области.</strong></p>
<p>Мы выполняем любые сопутствующие работы - от укладки плитки и замены слива до любых сантехнических работ, чтобы Вам не пришлось обращаться в десяток других фирм для завершения ремонта в ванной комнате.</p>
<p>Существует, на данный момент, 3 способа реставрации ванн: эмалировка ванн кистью, наливная ванна из жидкого акрила или стакрила и акриловый вкладыш (ванна в ванну).</p>
<p><strong>Каждый способ реставрации ванны решает разные задачи.</strong> Простая покраска (эмалировка) - для максимальной экономии, глубокое восстановление поверхности ванны жидким акрилом - для длительного использования, и акриловый вкладыш - для ванн с глубокими повреждениями и сколами.</p>
<p>Реставрация ванны обойдется вам в несколько раз дешевле, чем покупка новой ванны и тем более не потребуются дополнительные затраты на ремонт в ванной комнате.</p>
<p>А самое главное, <span class="akcenttext">Ваша ванна по внешнему виду и сроку службы, будет как новая!!!</span></p>
<p>Все используемые материалы проверенны нашим многолетним опытом на качество и долговечность.</p>
<p>Исходя из нашего многолетнего опыта работы, отбросив большое количество плохо зарекомендовавших себя материалов, путем проб и ошибок, Мы выбрали лучшие материалы от лучших производителей со 100% гарантией качества и долговечности.</p>
<p>Все используемые нами материалы соответствуют требованиям ГОСТ, безопасность подтверждена сертификатами и гигиеническими заключениями.</p>
</div></div></div></div>
<div id="uslugi" class="uslugi"><div class="cBlock"><h1 class="mainzaglavie">Способы реставрации:</h1>
<div class="EmalBl borderBlocks"><h2 class="ZaglBl">Эмалировка ванн</h2><p class="PsnizuH2">(покраска кистью)</p><img src="images/emalirovka.jpg" class="borderBlocks" alt="Эмалировка ванн в Гродно. Покраска кисточкой."><p class="P_Bl">Самый дешевый и простой способ реставрации ванны.</p><div class="Div_ul_emal"><ul><li><p class="podhodit">Идеально подходит для тех, кто сдает или снимает квартиру.</p></li><li><p>Эмаль наносится кисточкой в 2 - 3 слоя.</p></li><li><p>Толщина слоя: 0,3 - 0,5 мм.</p></li><li><p>Срок службы: 3 - 5 лет.</p></li><li><p>Стоимость: от <span class="Uslugi_cena">120 руб.</span></p></li><li><p class="consultUslugi"><a href="#cena">Выбрать материал</a></p></li></ul></div></div>
<div class="NalivBl borderBlocks"><h2 class="ZaglBl">Наливная ванна</h2><p class="PsnizuH2">(жидкий акрил, стакрил)</p><img src="images/naliv.jpg" class="borderBlocks" alt="Наливная ванна из жидкого акрила в Гродно."><p class="P_Bl">Самый лучший  и долговечный способ реставрации ванны.</p><div class="Div_ul_emal"><ul><li><p class="podhodit">Подходит для тех, кому важно качество и долговечность покрытия.</p></li><li><p>Жидкий акрил наливается по поверхности ванны.</p></li><li><p>Толщина слоя: 1,2 - 7,6 мм.</p></li><li><p>Срок службы: до 20 лет.</p></li><li><p>Стоимость: от 170 руб.</p></li><li><p class="consultUslugi"><a href="#cena">Выбрать материал</a></p></li></ul></div></div>
<div class="AkrilBl borderBlocks"><h2 class="ZaglBl">Акриловый вкладыш</h2><p class="PsnizuH2">(ванна в ванну)</p><img src="images/AkrilicVkladish.jpg" class="borderBlocks" alt="Акриловый вкладыш в Гродно."><p class="P_Bl">Хороший, но самый дорогой из всех методов реставрации ванн.</p><div class="Div_ul_emal"><ul><li><p class="podhodit">Подходит для ванн с глубокими сколами и повреждениями.</p></li><li><p>В старую ванну вклеивается новый вкладыш (ванна в ванну).</p></li><li><p>Толщина слоя: 1,5 - 2 мм.</p></li><li><p>Срок службы: 10 - 15 лет.</p></li><li><p>Стоимость: от 350 руб.</p></li><li><p class="consultUslugi"><a href="#cena">Выбрать материал</a></p></li></ul></div></div><div class="clear"></div>
<div class="Bl_pod_usl borderBlocks"><h3>Мы реставрируем любые ванны, поддоны, раковины, в любом состоянии и любой сложности!!!</h3><h4>Работаем в Гродно и по всей Гродненской области за наличный и безналичный расчет!</h4></div></div></div>
<?php include "Incl/processRestorations.php";?>
<div id="naschi_raboti" class="Land4Galerry cBlock"><h2 class="mainzaglavie">Наши работы</h2>
<div class="SpanDoPosle"><span class="before">До</span><span class="after">После</span></div>
<div class="WrappGalerryBox"><div class="videoObzor"><span>Видео</span></div><div class="naschComment"><span>Наш комментарий:</span></div>			
<div id="imgBox1">
<div class="FotoDoPosle">
<img src="images/galery/grodno/grodno_do1.jpg" alt="Наливная ванна в Гродно. Фотографии до покраски нанесения жидкого акрила Пластол">
<img class="galeryImgAfter" src="images/galery/grodno/grodno_posle1.jpg" alt="Восстановление ванны жидким акрилом в Гродно. Фотографии после нанесения жидкого акрила Пластол">
</div>
<div id="VideoComent1" class="videoComents"><iframe id="vid1" frameborder="0" allowfullscreen></iframe><script type="text/javascript">openVideo();</script></div><div class="clear"></div>
<div class="commentFoto"><p><strong>Гродно, ул. Ожешко.</strong> Ванна размером 1,5 м. Поверхность ванны была в ужасном состоянии!</p><p><strong>Причина:</strong> для чистки ванны использовали средства, содержащие сильные кислоты.</p><p><strong>Последствия:</strong> Поверхность ванны пришла в полную негодность, заводская эмаль истерлась на 76%, местами до чугуна, появилась сильная шероховатость и глубокие поры. Мыть ванну от грязи стало очень сложно.</p><p><strong>Устранение:</strong> Для реставрации использовали материал Премиум класса, с самым толстым слоем. Восстановление происходило по методу наливной ванны из жидкого акрила компании Plastall, произведенный совместно с Pabrec d.o.o (Slovenia, EU).</p></div>
</div>
<div id="imgBox2">
<div class="FotoDoPosle">
<img src="images/galery/grodno/grodno_do2.jpg" alt="Наливная ванна в Гродно. Фотографии до покраски и после нанесения жидкого акрила Пластол">
<img class="galeryImgAfter" src="images/galery/grodno/grodno_posle2.jpg" alt="Наливная ванна в Гродно. Фотография после нанесения жидкого акрила Пластол">
</div>
<div id="VideoComent2" class="videoComents"><iframe id="vid2" frameborder="0" allowfullscreen></iframe></div><div class="clear"></div>
<div class="commentFoto"><p><strong>Гродно, ул. А.Мицкевича.</strong> Ванна размером 1,2 м. На поверхности ванны были шероховатость и отложение водного камня!</p><p><strong>Причина:</strong> Использование средств, содержащие сильные кислоты, повышенная жесткость воды и несвоевременный уход за ванной.</p><p><strong>Последствия:</strong> Поверхность ванны стала шершавой, водный камень отлаживался, из-за чего, на ванне появились коричневые несмываемые пятна и разводы.</p><p><strong>Устранение:</strong> Восстановление происходило методом наливной ванны из жидкого акрила.</p></div>
</div>
<div id="imgBox3">
<div class="FotoDoPosle"><img src="images/galery/grodno/grodno_do3.jpg" alt="Наливная ванна в Гродно. Фотографии до покраски наливным акрилом">
<img class="galeryImgAfter" src="images/galery/grodno/grodno_posle3.jpg" alt="Реставрация ванны жидким акрилом в Гродно. После нанесения наливного акрила Пластол">
</div>
<div id="VideoComent3" class="videoComents"><iframe id="vid3" frameborder="0" allowfullscreen></iframe></div><div class="clear"></div>
<div class="commentFoto"><p><strong>Гродно, ул. Терешковой.</strong> Ванна размером 1,5 м. Поверхность ванны имела шероховатость.</p><p><strong>Причина:</strong> Использование средств, содержащие сильные кислоты.</p><p><strong>Последствия:</strong> Поверхность ванны стала шершавой, местами заводская эмаль была разьеденна до чугуна. Мыть ванну приходилось часто и затрачивать на это большие усилия.</p><p><strong>Устранение:</strong> Так как в квартире был маленький ребенок, реставрация происходила наливным акрилом Премиум класса, без запаха и пыли.</p></div>
</div>
<div class="GallButtn"><img class="prevGall" src="images/Bg/prev.png" alt="Смотреть предыдущую работу по восстановлению эмалевого покрытия ванны в Гродно." onclick="getImgBlock('false');"><img class="nextGall" src="images/Bg/next.png" alt="Посмотреть следующую нашу работу как мы красили ванну в Гродно." onclick="getImgBlock('true');"></div>
</div></div>
<div id="otzivi"><div class="cBlock">	
<h2 class="mainzaglavie">Отзывы</h2>
<div class="Video_Otzivs"><h3 class="Zagl_Text_otzive">Клиенты говорят о нас:</h3>
<div class="VideoOtziv1"><iframe id="VideoOtz1" src="https://www.youtube.com/embed/1s0ANX15k9g?rel=0" frameborder="0" allowfullscreen></iframe></div>
<div class="VideoOtziv2"><iframe id="VideoOtz2" src="https://www.youtube.com/embed/Da9mzKJhbZE?rel=0" frameborder="0" allowfullscreen></iframe></div>
<div class="VideoOtziv3"><iframe id="VideoOtz3" src="https://www.youtube.com/embed/SRiUFw4zf9g?rel=0" frameborder="0" allowfullscreen></iframe></div>
</div><div class="clear"></div>
<div class="WrapotzivText"><h3 class="Zagl_Text_otzive">Клиенты пишут нам:</h3>
<div id="otzivBlock1">
<div class="otziveWrap"><p><span class="skobki">"</span>Моей ванне уже много лет, более 30. Была очень страшная. Заказала эмалировку у другого мастера. Эмалировка порадовала меня только примерно 7 месяцев и начала в отдельных местах лущится. Гарантия имелась на 1 год. Звонила по телефону оставленному мне. Того мастера так и не нашла, так как номер уже не существует. Из интернета узнала, что эмалировка не оправдывающий себя способ, а лучше наливная ванна. Что я и сделала. Пользуюсь более года. Гарантия на 3 года согласно оставленного договора, с печатью. Этого думаю, что если что, то найду. Пока довольна. Надеюсь прослужит как и обещал 20 лет.<span class="skobki">"</span></p><h3>Татьяна, г. Гродно, ул. Курчатова</h3></div>
<div class="otziveWrap"><p><span class="skobki">"</span>Благодарна Дмитрию за реставрацию ванны жидким акрилом. Накануне Нового года у меня практически новая, такая белая и блестящая ванна. Я никогда и подумать не могла, что можно теперь в нее спокойно ложиться не задумываясь, что поцарапаешь определенный участок тела. Ура, наконец-то я это сделала!<span class="skobki">"</span></p><h3>Галина, г. Лида, ул. Космонавтов</h3></div>
<div class="otziveWrap"><p><span class="skobki">"</span>Заказывал ванну у Дмитрия, предложил сделать пластолом, т.к. ванна была в плачевном состоянии. Получилось ооочень хорошо! Убрали ржавчину, зашпаклевали сколы эмали так, что сколов и ржавчины на ванне, как-будто и не было. сделали все аккуратно и не долго. И действительно, как и обещали, без пыли и запаха. Оставили официальные документы и дали гарантию. Жена довольна!<span class="skobki">"</span></p><h3>Юра, г. Волковыск, ул. Социалистическая</h3></div>
</div>
<div id="otzivBlock2">
<div class="otziveWrap"><p><span class="skobki">"</span>Добрый день! Хотелось бы, поделиться, так сказать, опытом. В процессе ремонта в ванной  комнате, в ванну насыпалось много всякого мусора, цемента и фуги и у мастера несколько раз падал разный инструмент, оставляя на самой ванне сколы. С мужем долго думали что делать с ванной — выбросить или восстановить. Начали обзванивать мастеров и только на этом сайте нам всё подробно объяснили. Из целой кучи разных материалов краски подобрали оптимальную для нашей ванны, производства пластолл. Действительно краска оказалась без запаха! Результатом очень довольны! А какая белоснежная стала ванна, вам просто не передать словами!<span class="skobki">"</span></p><h3>Ольга, г. Гродно, ул. Домбровская</h3></div>
<div class="otziveWrap"><p><span class="skobki">"</span>Около 4 лет заказывал реставрацию ванны жидким стакрилом. Ванна получилась как новая. Я остался даволен (заказывал у Дмитрия). Стал делать ремонт в ванной комнате. В процессе ремонта упал топор, с высоты примерно 2 м на ванну. Ванну до этого укрыл пленкой. Сильно расстроился. Какого было удивление, когда снял пленку и нашел в ванне только 2 небольших скола. Похоже, что материал действительно стойкий. Позвонил Дмитрию, объяснил ситуацию. Так он на следующий день приехал и замазал эти сколы совершенно бесплатно! Я был очень удивлен такому сервису!</p><h3>Андрей, г. Дятлово, ул.Чапаева</h3></div>
<div class="otziveWrap"><p><span class="skobki">"</span>Долго я не выбирал, сделать мне ванну жидким акрилом или купить новую ванну. Я просто увидел, как сделали моим родителям ванну. Мне понравилось. Я даже не думал, что так может получиться красиво. Теперь и у меня ванна как новая. Не понимаю, зачем покупать новую ванну, если старую можно покрасить?</p><h3>Сергей, г. Новогрудок, ул.Юбилейная</h3></div>
</div>
<div id="otzivBlock3">
<div class="otziveWrap"><p><span class="skobki">"</span>Делая ремонт в ванной комнате сама ванна пришла в негодность. Поэтому встал вопрос о замене ванной или реставрации. Перелопатив интернет решились на реставрацию. Обратились к ребятам. Перед работой нам детально все объяснили. Приехали и буквально за два часа и ванна стала как новая. Огромное Вам спасибо, мы остались очень довольны! Обязательно будем рекомендовать вас всем знакомым.</p><h3>Олег, г. Лида, ул.Мицкевича</h3></div>
<div class="otziveWrap"><p><span class="skobki">"</span>Переехали жить на другую квартиру, где раньше жили пенсионеры. Ванна была в таком ужасном состоянии, что половины эмали уже не было, а только чугун светился. Обратились к Дмитрию, так он нам в день заказа прямо и сделал. Выглядит просто великолепно. Все довольны, особенно дети.</p><h3>Виктория, г. Вороново, ул.Советская</h3></div>
<div class="otziveWrap"><p><span class="skobki">"</span>Как-то приехали к знакомым в Лиду, а они ремонт закончили, мы зашли в ванную комнату и всех поразила ванна. Мы все думали, что это абсолютна новая ванна и до последнего не верили, пока хозяин не показал старое фото. Реставрация была произведена на очень высоком уровне. Поэтому по приезду в Минск было решено и себе заказать реставрацию, друг дал телефончик и ребята подъехали, все красиво и самое главное качественно сделали. Еще раз огромное спасибо вам ребята!</p><h3>Мария, г. Минск, ул.Ольшевского</h3></div>
</div>
<div class="controls"><img class="prev" src="images/Bg/prev.png" alt="Смотреть отзывы на наливную ванну жидким акрилом в Гродно." onclick="getOtziv('false');"><img class="next" src="images/Bg/next.png" alt="Отзывы на реставрацию ванн в Гродно" onclick="getOtziv('true');"></div>
</div>
<div class="more_OtzivesText"><h5>Еще отзывы</h5></div>
<div class="AddOtziv"><h4 id="createOtzive">Написать отзыв</h4>
<script type="text/javascript">document.getElementById("createOtzive").onclick=addOtzive;</script></div>
<div id="OtzBox" class="WrappModal"><div id="Otzshadow" class="shadow"></div>
<div id="addOtziveModalW" class="ModalBox">
<div id="closeAddOtzive" class="close"><img src="images/Bg/close.png" alt="Реставрация ванн, наливная ванна, эмалировка ванн в Гродно"></div>
<h2 class="OrderH2">Добавить отзыв</h2>
<form id="formOtzive" class="modalForm" method="post" action="action.php">
<input type="text" name="username" id="username" placeholder="Ваше имя" x-autocompletetype="name">
<input type="text" name="city" id="city" placeholder="Ваш город">
<textarea id="textOtz" name="textOtz" cols="50" placeholder="Ваш отзыв"></textarea><br>
<input type="button" class="submit" value="Добавить отзыв"  onclick="submitOtzive('Отзыв ванна люкс Гродно');">
</form></div></div>
<div id="wrappthxBox" class="WrappModal"><div id="thxShadow" class="shadow"></div><div class="ThanksBox"><div id="closeth" class="close"><img src="images/Bg/close.png" alt="Реставрация ванн жидким акрилом в Гродно"></div><div class="ok"></div><h3>Спасибо!</h3><p>Нам важно Ваше мнение</p></div></div>
</div></div>
<div id="wrapWidgetAccordeon" onclick="openModalBoxOrder('Перезвонить из аккордеонна, ванна люкс Гродно')">
<img class="callAcordeonImg" src="images/call.png" alt="Получить консультацию по реставрации ванны в Гродно">
<p class="AccordP">Хотите, мы Вам перезвоним?</p>
</div>
<?php include "Incl/Sertificats.php";?>
<div id="cena" class="Land6Cena cBlock"><h2 class="mainzaglavie">Наши цены</h2>
<div class="variation">	
<div class="costemalImg"><img class="costImg emalheight" src="images/emalirovkaCost.jpg" alt="Реставрация ванн в Гродненской области. Эмалировка ванн. Заказать восстановление эмалевого покрытия ванны в Гродно."></div>	
<div class="CostImgBlockOpis"><h3 class="Zagl_block_cena">Эмалировка ванн</h3><h5 class="Zagl_bottom">(покраска кистью)</h5><p>Эмалировка ванн – это самый экономный способ реставрации ванны.</p><p>Наносится эмалью, таких компаний как:</p><p class="Company">Tikkurila, Ecovanna, БЭП.</p><p>В состав материалов входит сырье зарубежных производителей:</p><div class="imKompEmal"><img src="images/Materials/componentsEmal.jpg" alt="Компоненты входящие в состав материалов для эмалировки в Гродно."></div><p>Срок службы: 3-5 лет.</p></div><div class="clear"></div>
<div class="materialsWrap">
<div class="materlsblock mat1 borderBlocks"><h4>Эмалировка №1</h4><img src="images/Materials/reafleks.jpg" alt="Финский материал для покраски ванны методом эмалировки в Гродно."><p class="P1">Эмаль Реафлекс</p><p class="P2">(Финляндия, Tikkurila)</p><div class="coment_matBlock"><p>Время высыхания: 7 дней.</p><p>Реальный срок службы: до 3 лет!</p></div><table><tr class="firstTr"><td>Размер ванны:</td><td>Цена:</td></tr><tr><td>1,5 м.</td><td class="redCena">120 руб.</td></tr></table><div class="orderButton" onclick="openModalBoxOrder('Эмалировка Реафлекс Тиккурила наши цены Гродно')"><span>Заказать</span></div></div>
<div class="materlsblock borderBlocks"><h4>Эмалировка №2</h4><img src="images/Materials/epoxin.jpg" alt="Российский материал для эмалировки по всей Гродненской области."><p class="P1">Эмаль Эпоксин 51с</p><p class="P2">(Россия, БЭП)</p><div class="coment_matBlock"><p>Время высыхания: 4 дня.</p><p>Реальный срок службы: до 3 лет!</p></div><table><tr class="firstTr"><td>Размер ванны:</td><td>Цена:</td></tr><tr class="cenamtrls"><td>1,5 м.</td><td class="redCena">130 руб.</td></tr></table><div class="orderButton" onclick="openModalBoxOrder('Эмалировка Эпоксин 51с наши цены ванналюксГродно')"><span>Заказать</span></div></div>
<div class="materlsblock borderBlocks"><h4>Эмалировка №3</h4><img src="images/Materials/eemalka.jpg" alt="Российская эмаль для восстановления старой ванны методом покраски кисточкой или эмалировка в Гродно, Щучине, Волковыске, Слониме."><p class="P1">Эмаль ЭкоЭмалька</p><p class="P2">(Россия, Ecovanna)</p><div class="coment_matBlock"><p>Время высыхания: 2 дня.</p><p>Реальный срок службы: до 5 лет!</p></div><table><tr class="firstTr"><td>Размер ванны:</td><td>Цена:</td></tr><tr><td>1,5 м.</td><td class="redCena">130 руб.</td></tr></table><div class="orderButton" onclick="openModalBoxOrder('Эмалировка Экоэмалька наши цены Гродно')"><span>Заказать</span></div></div><div class="clear"></div></div></div>
<div class="variation">
<div class="costemalImg"><img class="costImg nalivimg" src="images/nalivCost.jpg" alt="Наливная ванна из жидкого акрила в Гродно, Лиде, Слониме, Волковыске, Дятлове, Кореличи, Щучине, Зельве, Вороново."></div>	
<div class="CostImgBlockOpis"><h3 class="Zagl_block_cena">Наливная ванна</h3><h5 class="Zagl_bottom">(жидкий акрил, стакрил)</h5><p>Наливная ванна - это идеальный способ реставрации ванны по соотношению цена/качество.</p><p>В состав материалов входит сырье зарубежных производителей:</p><div class="imKompNaliv"><img src="images/Materials/NalivKomponents.jpg" alt="Компоненты входящие в состав материалов для наливной ванны из жидкого акрила, стакрила и наливного акрила Пластол"></div></div><div class="clear"></div>
<div class="materialsWrap"><h4 class="Zagl_class">Материалы Эконом класса</h4><p class="osobennosti_Class">Отличительные особенности эконом класса: Тонкий слой покрытия, желтеют со временем (через 1-2 года), присутствуют разбавители (ксилол, ацетон или нонилфенол) и поэтому имеют резкий запах, реальный срок службы до 7 лет.</p>
<div class="materlsblock mat1 borderBlocks"><h4>Эконом №1</h4><img src="images/Materials/yarli.jpg" alt="Материал жидкий акрил Ярли, для реставрации ванны в Гродно и в Гродненской области, экономный вариант."><p class="P1">ЯрЛи Соат</p><p class="P2">(Россия, ЯрЛи)</p><p class="comentVibora">Материал эконом класса!</p><div class="coment_matBlock"><p>Толщина слоя: тонкий.</p><p>Реальный срок службы: до 7 лет!</p></div><table><tr class="firstTr"><td>Размер ванны:</td><td>Цена:</td></tr><tr><td>1,5 м.</td><td class="redCena">170 руб.</td></tr></table><div class="orderButton" onclick="openModalBoxOrder('наливная ванна Ярли эконом 1 ванна люкс Гродно')"><span>Заказать</span></div></div>
<div class="materlsblock borderBlocks"><h4>Эконом №2</h4><img src="images/Materials/ecolor.jpg" alt="Жидкий акрил от Эколора, один из самых экономных вариантов для восстановления ванн методом налива в Гродненской области."><p class="P1">Stacril Ecolor</p><p class="P2">(Россия, Эколор)</p><p class="comentVibora">Материал эконом класса!</p><div class="coment_matBlock"><p>Толщина слоя: тонкий.</p><p>Реальный срок службы: до 7 лет!</p></div><table><tr class="firstTr"><td>Размер ванны:</td><td>Цена:</td></tr><tr><td>1,5 м.</td><td class="redCena">175 руб.</td></tr></table><div class="orderButton" onclick="openModalBoxOrder('наливная ванна стакрилом Эколор эконом 2 ванна люкс Гродно')"><span>Заказать</span></div></div>
<div class="materlsblock borderBlocks"><h4>Эконом №3</h4><img src="images/Materials/finnacryl.jpg" alt="Материал для покраски ванны наливным способом Финакрил в Гродно."><p class="P1">Finnacril</p><p class="P2">(Россия, Рестванна)</p><p class="comentVibora redCena">Лучший в эконом классе!</p><div class="coment_matBlock"><p>Толщина слоя: средняя.</p><p>Реальный срок службы: до 7 лет!</p></div><table><tr class="firstTr"><td>Размер ванны:</td><td>Цена:</td></tr><tr><td>1,5 м.</td><td class="redCena">170 руб.</td></tr></table><div class="orderButton" onclick="openModalBoxOrder('наливная ванна Финакрилом эконом 3 Гродно')"><span>Заказать</span></div></div><div class="clear"></div>
<h4 class="Zagl_class">Материалы Стандарт класса</h4><p class="osobennosti_Class">Отличительные особенности стандарт класса: Более толстый слой покрытия, более устойчивы к разрушению полимерной цепи и потере прочности в ряде точек структуры покрытия, по сравнению с эконом классом, но тем не менее приобретают различные оттенки желтого (через 2-3 года), присутствуют разбавители (ксилол, ацетон или нонилфенол), имеют резкий запах, реальный срок службы до 10 лет. Все вышесказанное касается только материалов стандарт №1 и стандарт №2.</p>		
<div class="materlsblock mat1 borderBlocks"><h4>Стандарт №1</h4><img src="images/Materials/bep.jpg" alt="Материал стакрил для наливной ванны от БЭП, хороший материал, с толстым слоем, но желтеет."><p class="P1">Stacril</p><p class="P2">(Россия, БЭП)</p><p class="comentVibora">Материал стандарт класса!</p><div class="coment_matBlock"><p>Толщина слоя: средняя.</p><p>Реальный срок службы: до 10 лет!</p></div><table><tr class="firstTr"><td>Размер ванны:</td><td>Цена:</td></tr><tr><td>1,5 м.</td><td class="redCena">180 руб.</td></tr></table><div class="orderButton" onclick="openModalBoxOrder('наливная ванна стакрилом БЭП стандарт №1 Гродно')"><span>Заказать</span></div></div>
<div class="materlsblock borderBlocks"><h4>Стандарт №2</h4><img src="images/Materials/ecovlux.jpg" alt="Материал от Экованны, один из экономных вариантов для наливной ванны в Гродно."><p class="P1">Ecovanna</p><p class="P2">(Россия, Экованна)</p><p class="comentVibora">Материал стандарт класса!</p><div class="coment_matBlock"><p>Толщина слоя: средняя.</p><p>Реальный срок службы: до 10 лет!</p></div><table><tr class="firstTr"><td>Размер ванны:</td><td>Цена:</td></tr><tr><td>1,5 м.</td><td class="redCena">170 руб.</td></tr></table><div class="orderButton" onclick="openModalBoxOrder('наливная ванна акрилом люкс стандарт №2 Гродно')"><span>Заказать</span></div></div>
<div class="materlsblock borderBlocks"><h4>Стандарт №3</h4><img class="imgTitan" src="images/Materials/plastallTitan.png" alt="Самый лучший материал для реставрации ванны методом наливной ванны это Пластол в Гродно, Щучине, Волковыске, Лиде, Дятлово!"><p class="P1">PlastAll Titan</p><p class="P2">(Россия, Пластол)</p><p class="comentVibora redCena">Лучший в стандарт классе!</p><div class="coment_matBlock"><p>Не желтеет и без запаха.</p><p>Реальный срок службы: до 15 лет!</p></div><table><tr class="firstTr"><td>Размер ванны:</td><td>Цена:</td></tr><tr><td rowspan="2">1,5 м.</td><td class="oldPrice">215 руб.</td></tr><tr><td class="redCena">205 руб.</td></tr></table><div class="orderButton" onclick="openModalBoxOrder('наливная ванна Пластолом Титан стандарт №3 Гродно')"><span>Заказать</span></div></div><div class="clear"></div>
<h4 class="Zagl_class">Материалы Премиум класса</h4><p class="osobennosti_Class">Отличительные особенности Премиум класса: Абсолютно без запаха(не содержат вредных для здоровья компонентов, запрещенных в Евросоюзе)! Не желтеют в течении всего срока эксплуатации ванны! Устойчивы к разрушению материала, появлению трещин и отслоений! Высочайшая степень белизны и глянца! Сильнейшая степень прилипания(адгезии) к старой ванне обеспечивается еще, и благодаря использованию специального средства для подготовки ванны! Сертифицированны в Беларуси! Рецептура испытанна в Евросоюзе, США, Канаде, Австралии и в Южной Африке!</p>
<div class="materlsblock mat1 borderBlocks"><h4>Премиум №1</h4><img class="imgPremium" src="images/Materials/PlastallSuper.png" alt="Пластол супер - материал с самым толстым слоем покрытия для наливной ванны в Гродненской области!"><p class="P1">PlastAll Super</p><p class="P2">(Россия, Пластол)</p><p class="comentVibora">Материал премиум класса</p><div class="coment_matBlock"><p>Срок высыхания: 16 часов.</p><p>Толщина слоя: высокая.</p></div><table><tr class="firstTr"><td>Размер ванны:</td><td>Цена:</td></tr><tr><td rowspan="2">1,5 м.</td><td class="oldPrice">225 руб.</td></tr><tr><td class="redCena">210 руб.</td></tr></table><div class="orderButton" onclick="openModalBoxOrder('наливная ванна пластол супер премиум №1 Гродно')"><span>Заказать</span></div></div>
<div class="materlsblock borderBlocks"><h4>Премиум №2</h4><img class="imgPremium" src="images/Materials/plastallPremium.png" alt="Пластол премиум - лучший материал для наливной ванны в Гродно!"><p class="P1">PlastAll Premium</p><p class="P2">(Россия, Пластол)</p><p class="comentVibora">Материал премиум класса</p><div class="coment_matBlock"><p>Время высыхания: 1 день.</p><p>Реальный срок службы: до 20 лет!</p></div><table><tr class="firstTr"><td>Размер ванны:</td><td>Цена:</td></tr><tr><td rowspan="2">1,5 м.</td><td class="oldPrice">235 руб.</td></tr><tr><td class="redCena">215 руб.</td></tr></table><div class="orderButton" onclick="openModalBoxOrder('наливная ванна пластол премиум №2 Гродно')"><span>Заказать</span></div></div>
<div class="materlsblock borderBlocks"><h4>Премиум №3</h4><img class="imgPremium" src="images/Materials/plastallClassic.png" alt="Самый лучший материал для реставрации ванны в Гродно методом наливной ванны это Пластол классик!"><p class="P1">PlastAll Classic (Ecopel)</p><p class="P2">(Россия, Пластол)</p><p class="comentVibora redCena">Лучший в премиум классе</p><div class="coment_matBlock"><p>Максимальное качество!</p><p>Европейская рецептура!</p></div><table><tr class="firstTr"><td>Размер ванны:</td><td>Цена:</td></tr><tr><td rowspan="2">1,5 м.</td><td class="oldPrice">245 руб.</td></tr><tr><td class="redCena">230 руб.</td></tr></table><div class="orderButton" onclick="openModalBoxOrder('наливная ванна классик премиум №3 ванна-люкс Гродно')"><span>Заказать</span></div></div></div><div class="clear"></div></div>
<?php include "../Incl/vozmogniedoplati.php";?><div class="clear"></div>
<div class="variation"><div class="costemalImg"><img class="costImg vkladHeight" src="images/vkladishCost.jpg" alt="Акриловый вкладыш производства Искомп в Гродно и по всей Гродненской области."></div><div class="CostImgBlockOpis"><h3 class="Zagl_block_cena">Акриловый вкладыш</h3><h5 class="Zagl_bottom">(вставка в ванну)</h5><p>Акриловый вкладыш – это вклеивание новой ванны в старую (ванна в ванну).</p><p>Акриловый вкладыш лучше делать, если поверхность ванны имеет глубокие повреждения, сколы и браки литья.</p><p class="beforeCompany">Мы используем акриловые вкладыши, произведенные компанией: ИСКомп.</p><p>Изготавливается вкладыш из двухслойного листа, верхний слой – это сантехнический акрил (эстетический вид), а нижний слой состоит из АБС-пластика (усиливающий слой).</p></div><div class="clear"></div><div class="materialsWrap"><div class="m1Vkladish borderBlocks"><h4>Акриловый вкладыш</h4><img src="images/Materials/iscomp.jpg" alt="Акриловый вкладыш Полифлекс в Гродно."><p class="P1">Poliflex</p><p class="P2">(Россия, ИСКомп)</p><div class="coment_matBlock"><p class="vkladish_coment_P">Реальный срок службы: до 20 лет!</p></div><table><tr class="firstTr"><td>Размер ванны:</td><td>Цена:</td></tr><tr><td>1,5 м.</td><td class="redCena">350 руб.</td></tr></table><div class="orderButton" onclick="openModalBoxOrder('акриловый вкладыш в Гродно')"><span>Заказать</span></div></div></div></div><div class="clear"></div></div>
<div id="OrderBoxCeni" class="WrappModal"><div id="Ordershadow" class="shadow"></div>
<div id="ModalBoxOrder" class="ModalBox borderBlocks">
<div id="closeModal" class="close"><img src="images/Bg/close.png" alt="Реставрация ванн жидким акрилом в Гродно"></div>
<h2 class="OrderH2 mainzaglavie zagl">Оставить заявку</h2>
<form id="OrderForm" class="modalForm" method="post" action="action.php">
<input type="text" name="usernameOrder" id="usernameOrder" placeholder="Ваше имя" x-autocompletetype="name">
<input type="text" name="cityOrder" id="cityOrder" placeholder="Ваш город">
<input type="text" name="phone" id="phone" placeholder="Ваш телефон для связи" required="required">
<input type="button" class="submit" value="Оставить заявку"  onclick="submitOrder();">
</form><p>Политика конфиденциальности: Мы не сохраняем и не передаем Ваши данные третьим лицам!</p></div></div>
<div id="ContThanksOrder" class="WrappModal"><div id="ShadowThanksOrder" class="shadow"></div><div class="ThanksBox"><div id="closeImg" class="close"><img src="images/Bg/close.png" alt="Покраска ванны в Гродно"></div><div class="ok"></div><h3>Спасибо за заявку!</h3><p>Мы обязательно перезвоним Вам!</p></div></div>
<footer><div id="footer" class="cBlock"><div class="infoFooter"><p id="nameFooter">&copy;<a href="/grodno/"><strong> vanna-lux.by</strong></a></p><p class="pravaFoot">Все права защищены.</p></div><div class="callusFooter"><div class="phoneImg"><img src="images/a1_logo.png" alt="Заказать реставрацию ванны в Гродно."><div class="numberphone"><a class="header_phone" href="tel:+375296954525">+375(29) 695-45-25</a></div></div><div class="phoneImg"><img class="mtslogo" src="images/mtc.png" alt="Заказать покраску ванны в Гродно."><div class="numberphone"><a class="header_phone" href="tel:+375292504525">+375(29) 250-45-25</a></div></div><div class="timework">ежедневно с 8.00 до 22.00</div><div><span class="consult" onclick="openModalBoxOrder('получить консультацию телефоны в футере ванна люкс Гродно')">Консультация у мастера</span></div></div>
<?php include "../Incl/footerCityGrodno.php";?>
</div></footer></body></html>